article/urls.py
from django.urls import path
from . import views
app_name = 'article'
urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
]

article/models.py
from django.db import models

# Create your models here.
# django内建User模型
from django.contrib.auth.models import User
from django.utils import timezone

# 文章数据模型
class ArticlePost(models.Model):

    # 作者，级联删除
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章标题
    title = models.CharField(max_length=100)
    # 文章正文，保存大量文本
    body = models.TextField()
    # 文章创建时间
    created = models.DateTimeField(default=timezone.now())
    # 修改时间，auto_now=True自动写入每次更新时间
    updated = models.DateTimeField(auto_now=True)

    # 定义元数据
    class Meta:
       # 模型返回的数据按创建时间倒序排列
        ordering = ('-created',)
    def __str__(self):
        # 返回文章的标题
        return self.title

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User

from .models import ArticlePost
from .forms import ArticlePostForm

import markdown
# Create your views here.


def article_safe_delete(request, id):
    if request.method == "POST":
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

def article_create(request):
    if request.method == "POST":
        # 将网页提交的数据赋值到表单实例
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            # 保存数据但不提交到数据库
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=1)
            # 保存到数据库
            new_article.save()

            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写")
    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)

def article_list(request):
    articles = ArticlePost.objects.all()
    # 传递给模板
    context = {'articles':articles}
    # 载入模板返回context
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    #   渲染markdown语法
    article.body = markdown.markdown(article.body, extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
    ])
    context = {'article':article}
    return render(request, 'article/detail.html', context)

templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} 写文章 {% endblock title %}
{% block content %}
<div class="container">
     <div class="row">
         <div class="col-12">
             <br>
             <form method="post" action=".">
                 {% csrf_token %}
                 <!-- 标题 -->
                 <div class="form-group">
                     <label for="title">文章标题</label>
                     <input type="text" class="form-control" id="title" name="title">
                 </div>
                 <!-- 正文 -->
                 <div class="form-group">
                     <label for="body">文章正文</label>
                     <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                 </div>
                 <button type="submit" class="btn btn-primary">完成</button>
             </form>
         </div>
     </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
文章详情
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <h1 class="clo-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}
            <a href="#" onclick="confirm_safe_delete()">删除文章</a>
        </div>
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>
    </div>
</div>
    <form
        style="display:none;"
        id="safe_delete"
        action="{% url 'article:article_safe_delete' article.id %}"
        method="post"
        >
    {% csrf_token %}
    <button type="submit">发送</button>
    </form>
    <script>
    function confirm_safe_delete(){
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function(index, layero) {
                $('form#safe_delete button').click()
                layer.close(index)
            },
        })
    }
    </script>
{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    首页
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
            <div class="col-4 mb-4">
                <div class="card h-100">
                    <!-- 标题 -->
                    <h4 class="card-header">{{ article.title }}</h4>
                    <!-- 摘要 -->
                    <div class="card-body">
                        <p class="card-text">{{ article.body|slice:'100' }}...</p>
                    </div>
                    <!-- 注脚 -->
                    <div class="card-footer">
                        <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读文本</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/base.html
{% load staticfiles %}
<html lang="zh-cn">

<head>
    <meta charset="'utf-8">
    <!-- 网站标题 -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    <!-- 导航栏 -->
    {% include 'header.html' %}
    {% block content %}{% endblock content %}
    <!-- 注脚 -->
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
</body>
</html>

templates/footer.html
{% load staticfiles %}
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

templates/header.html
<!-- 导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">我的博客</a>
        <div>
            <!-- 导航入口 -->

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>

            </ul>
        </div>
    </div>
</nav>